import Button from "./Button";
import figma from "@figma/code-connect";
import type { ButtonProps } from "./Button";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

type FigmaButtonExampleProps = {
  variant:
    | "Primary"
    | "Secondary"
    | "Destructive"
    | "Ghost"
    | "Ghost muted"
    | "Ghost nav"
    | "Outline";
  size: "Default" | "Small" | "Large" | "Mini";
  roundness: "Default" | "Round";
  showLeftIcon?: boolean;
  showRightIcon?: boolean;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
};

const variantMap: Record<
  FigmaButtonExampleProps["variant"],
  NonNullable<ButtonProps["variant"]>
> = {
  Primary: "primary",
  Secondary: "secondary",
  Destructive: "destructive",
  Ghost: "ghost",
  "Ghost muted": "ghost-muted",
  "Ghost nav": "ghost-nav",
  Outline: "outline",
};

const sizeMap: Record<
  FigmaButtonExampleProps["size"],
  NonNullable<ButtonProps["size"]>
> = {
  Default: "default",
  Small: "sm",
  Large: "lg",
  Mini: "mini",
};

const roundnessToShape: Record<
  FigmaButtonExampleProps["roundness"],
  NonNullable<ButtonProps["shape"]>
> = {
  Default: "default",
  Round: "round",
};

figma.connect(
  Button,
  "https://www.figma.com/design/LHYOb1IKNLz2h5wrWeqcv7/shadcn-ui-%E2%80%93-Carrier1?node-id=9-1071&m=dev",
  {
    props: {
      variant: figma.enum("Variant", {
        primary: "Primary",
        secondary: "Secondary",
        destructive: "Destructive",
        ghost: "Ghost",
        "ghost-muted": "Ghost muted",
        "ghost-nav": "Ghost nav",
        outline: "Outline",
      }),
      size: figma.enum("Size", {
        default: "Default",
        sm: "Small",
        lg: "Large",
        mini: "Mini",
      }),
      roundness: figma.enum("Roundness", {
        default: "Default",
        round: "Round",
      }),
      showLeftIcon: figma.boolean("Show left icon"),
      showRightIcon: figma.boolean("Show right icon"),
      leftIcon: figma.instance("⮑ Left icon"),
      rightIcon: figma.instance("⮑ Right icon"),
    },
    example: (props: FigmaButtonExampleProps) => {
      const variant = variantMap[props.variant];
      const size = sizeMap[props.size];
      const shape = roundnessToShape[props.roundness];
      const showLeft = props.showLeftIcon;
      const showRight = props.showRightIcon;

      if (showLeft && showRight) {
        return (
          <Button
            variant={variant}
            size={size}
            shape={shape}
            iconPosition="both"
            leftIcon={props.leftIcon}
            rightIcon={props.rightIcon}
          />
        );
      }
      if (showLeft) {
        return (
          <Button
            variant={variant}
            size={size}
            shape={shape}
            iconPosition="left"
            icon={props.leftIcon}
          />
        );
      }
      if (showRight) {
        return (
          <Button
            variant={variant}
            size={size}
            shape={shape}
            iconPosition="right"
            icon={props.rightIcon}
          />
        );
      }
      return (
        <Button variant={variant} size={size} shape={shape} label="Click me" />
      );
    },
  }
);
